name: Build Precompiled Image for Raspberry Pi

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Cross-compile Go binary for ARM64
        run: |
          GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o whisperbin ./cmd/whisperbin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run Go tests
        run: go test -v -failfast ./...

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image (binary only)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/arm64
          tags: ghcr.io/${{ github.repository_owner }}/whisperbin:latest
